### ISSUE TITLE
Update: Failure on connect all figures on map, and update about current layout

### ISSUE THREAD

**Issue by PANDASANG1231** [UBC-MDS/datasci_salaries_py#29]
Hey guys, @artanzand @joshsia @SiqiTao 

I just finished the layout. But there is something I need to keep you updated on. 

 -  Failure on connecting everything to the map: I found that if I use add selection in Lecture 4, it only works in one Altair plot. As you can see in the screenshot below, if I put bar_chart together with the map, everything worked. When I put it in another Frame, it will show "Selector not found"
![image](https://user-images.githubusercontent.com/32384602/156231265-7d7c9a7b-b768-441b-95f4-6b742fad7ede.png)

 - Right now every plot is controlled by a drop-down list, and when you click one country, the map will change and every plot will change. Two screen shots are listed here
 
![image](https://user-images.githubusercontent.com/32384602/156232446-0e0f5d9d-d540-4535-a2ac-20b2855328a4.png)

![image](https://user-images.githubusercontent.com/32384602/156232513-30d562a7-33fd-479c-a737-551e0cd27b07.png)

**Comment by joshsia** [comment]
Thanks! Could you create a pull request so that we can see the code?

**Comment by joshsia** [comment]
Thanks so much for your work! Would it be possible to deploy this onto Heroku so that we can try out the widgets?

I also have a few questions/suggestions: (We don't have to implement everything this week, just the important ones. I could include the rest in the reflection document)

Image 2:
- Is this the default behaviour when the user first enters our dashboard?
- Do the plots show the distributions for all countries?
- Could we standardise the `Salary in USD` ticks? Also, is it possible to not have them all expressed in million `M`, and instead, have a mix of `k` and `M`?
- Could we standardise the grid lines in the plots? (e.g. the boxplot has vertical lines, the histogram has horizontal lines, and the age histogram has both)
- We'll probably need to add labels for widgets that aren't as obvious (like the slider)
- I think it would be better if the top bar for the dashboard title is not overlapped by the plot on the right
- The contrast between the predominant white background and the black background of the plot on the right seems a bit too big. It might be better if we make it a lighter gray?
- I think it would be better to standardise `Counts`, `Count of Records`, `Tot. Records` into one common name
- Would it be possible to further shrink the world map by cropping useless areas (top and bottom)?

Image 3:
- The world map's legend now has another encoding for opacity(?). Does this refer to any of our features or is it just a design choice?
- The histogram for age now seems to have white around the bars. In the previous image it just looked all blue. Was the code changed for this plot?
- The heatmap when a particular country is chosen looks a bit strange because the colour ranges from 0 to 3 records only. Would it be better to decrease the number of bins?
- It would be great if we could change the plot title depending on the selected country

**Comment by PANDASANG1231** [comment]
Thanks so much for your work! Would it be possible to deploy this onto Heroku so that we can try out the widgets?

I also have a few questions/suggestions: (We don't have to implement everything this week, just the important ones. I could include the rest in the reflection document)

Image 2:
- [X] Is this the default behaviour when the user first enters our dashboard?
- [X] Do the plots show the distributions for all countries?
   
**Yes, these are default behaviour and by default every plot shows the situation for all countries.**

- [ ] Could we standardise the `Salary in USD` ticks? Also, is it possible to not have them all expressed in million `M`, and instead, have a mix of `k` and `M`?
- [ ] Could we standardise the grid lines in the plots? (e.g. the boxplot has vertical lines, the histogram has horizontal lines, and the age histogram has both)
- [ ] We'll probably need to add labels for widgets that aren't as obvious (like the slider)
- [ ] I think it would be better if the top bar for the dashboard title is not overlapped by the plot on the right
- [ ] The contrast between the predominant white background and the black background of the plot on the right seems a bit too big. It might be better if we make it a lighter gray?
- [ ] I think it would be better to standardise `Counts`, `Count of Records`, `Tot. Records` into one common name
- [ ] Would it be possible to further shrink the world map by cropping useless areas (top and bottom)?

Image 3:
- [ ] The world map's legend now has another encoding for opacity(?). Does this refer to any of our features or is it just a design choice?
- [ ] The histogram for age now seems to have white around the bars. In the previous image it just looked all blue. Was the code changed for this plot?
- [ ] The heatmap when a particular country is chosen looks a bit strange because the colour ranges from 0 to 3 records only. Would it be better to decrease the number of bins?
- [ ] It would be great if we could change the plot title depending on the selected country

**Comment by joshsia** [comment]
About shrinking the world map, I meant zooming in and "cropping" the world map, maybe by playing around with the scale and translate parameters as in Lecture 4.
```
alt.Chart(world_map).mark_geoshape(
    fill='#2a1d0c', stroke='#706545', strokeWidth=0.5
).project(type='naturalEarth1', scale=500, translate=[140, 610])
```

About the world map legend, if you look at the third image, you see that there is a legend for `alpha`.

About the white borders around the `age` histogram bars. If you look at the second image, you see that all the histogram bars are blue which makes it look unseparated. But in the third image, there are white borders around each histogram bar.

**Comment by PANDASANG1231** [comment]
> About shrinking the world map, I meant zooming in and "cropping" the world map, maybe by playing around with the scale and translate parameters as in Lecture 4.
> 
> ```
> alt.Chart(world_map).mark_geoshape(
>     fill='#2a1d0c', stroke='#706545', strokeWidth=0.5
> ).project(type='naturalEarth1', scale=500, translate=[140, 610])
> ```
> 
> About the world map legend, if you look at the third image, you see that there is a legend for `alpha`.
> 
> About the white borders around the `age` histogram bars. If you look at the second image, you see that all the histogram bars are blue which makes it look unseparated. But in the third image, there are white borders around each histogram bar.

I think the first two are solved in the new PR now.

In the third one, do you think we should also change the bin_num, just as the heatmap? I think we can combine those two comments together

**Comment by joshsia** [comment]
Yeah, we can change the number of bins

**Comment by joshsia** [comment]
@PANDASANG1231 Yeah, don't worry about it, you can work on it on the weekend. In the meantime, I wrote that our current dashboard uses a dropdown menu to select a country in the reflection document.
